server:
  host: localhost
  port: 8080

microservice:
  host: localhost
  port: 8081

database:
  host: localhost
  port: 5432
  user: postgres
  password: ${DB_PASSWORD}
  name: go_calc_db
  ssl_mode: require